# Generated by Django 2.0.7 on 2018-08-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UEFA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teams', models.CharField(choices=[('Juventus', 'Juventus'), ('Tottenham', 'Tottenham')], max_length=64)),
            ],
        ),
    ]
